services:
  keycloak-service:
    image: quay.io/keycloak/keycloak:23.0.7
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      gestion-bien-network:

  postgres_db:
    image: postgres:15.1
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - gestion-bien-network
volumes:
  pgdata:
networks:
  gestion-bien-network:
    driver: bridge
