services:
  keycloak-service:
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    expose:
      - "8890"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - gestion-bien-network
  postgres_db:
    image: postgres:15.1
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - gestion-bien-network

  gestion-bien-database-service:
    image: postgres:15.1
    environment:
      POSTGRES_USER: gestion_bien_user
      POSTGRES_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: "exit 0"
    networks:
      - gestion-bien-network

  gestion-bien-discovery-service:
    build: ./discovery-service
    container_name: gestion-bien-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      gestion-bien-network:
  gestion-bien-gateway-service:
    build: ./gateway-service
    container_name: gestion-bien-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://gestion-bien-discovery-service:8761/eureka
    depends_on:
      - gestion-bien-discovery-service
    networks:
      gestion-bien-network:
  gestion-bien-bon-entre-service:
    build: ./bon-entree-service
    container_name: gestion-bien-bon-entree-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DATABASE_SERVICE_URL=jdbc:postgresql://gestion-bien-database-service:5432/bedb
      - DISCOVERY_SERVICE_URL=http://gestion-bien-discovery-service:8761/eureka
      - KEYCLOAK_SERVICE_URL_REALM=http://keycloak-service:8890/realms/gestion_bien
      - KEYCLOAK_SERVICE_URL_CERTS=http://keycloak-service:8890/realms/gestion_bien/protocol/openid-connect/certs
    depends_on:
      - gestion-bien-discovery-service
      - gestion-bien-database-service
    networks:
        gestion-bien-network:
  gestion-bien-bien-service:
    build: ./bien-service
    container_name: gestion-bien-bien-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - DATABASE_SERVICE_URL=jdbc:postgresql://gestion-bien-database-service:5432/productdb
      - DISCOVERY_SERVICE_URL=http://gestion-bien-discovery-service:8761/eureka
      - KEYCLOAK_SERVICE_URL_REALM=http://keycloak-service:8890/realms/gestion_bien
      - KEYCLOAK_SERVICE_URL_CERTS=http://keycloak-service:8890/realms/gestion_bien/protocol/openid-connect/certs
    depends_on:
      - gestion-bien-discovery-service
      - gestion-bien-database-service
      - gestion-bien-bon-entre-service
    networks:
      gestion-bien-network:
  gestion-bien-bon-sortie-service:
    build: ./bon-sortie-service
    container_name: gestion-bien-bon-sortie-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - DATABASE_SERVICE_URL=jdbc:postgresql://gestion-bien-database-service:5432/exvdb
      - DISCOVERY_SERVICE_URL=http://gestion-bien-discovery-service:8761/eureka
      - KEYCLOAK_SERVICE_URL_REALM=http://keycloak-service:8890/realms/gestion_bien
      - KEYCLOAK_SERVICE_URL_CERTS=http://keycloak-service:8890/realms/gestion_bien/protocol/openid-connect/certs
    depends_on:
      - gestion-bien-discovery-service
      - gestion-bien-database-service
      - gestion-bien-bien-service
    networks:
      gestion-bien-network:
  gestion-bien-inventaire-service:
    build: ./inventaire-service
    container_name: gestion-bien-inventaire-service
    ports:
      - "8084:8084"
    expose:
      - "8084"
    environment:
      - DATABASE_SERVICE_URL=jdbc:postgresql://gestion-bien-database-service:5432/inventorydb
      - DISCOVERY_SERVICE_URL=http://gestion-bien-discovery-service:8761/eureka
      - KEYCLOAK_SERVICE_URL_REALM=http://keycloak-service:8890/realms/gestion_bien
      - KEYCLOAK_SERVICE_URL_CERTS=http://keycloak-service:8890/realms/gestion_bien/protocol/openid-connect/certs
    depends_on:
      - gestion-bien-discovery-service
      - gestion-bien-database-service
      - gestion-bien-bien-service
    networks:
      gestion-bien-network:
networks:
  gestion-bien-network:
    driver: bridge

volumes:
  pgdata: